/**
 * Mode-aware level catalog loader.
 *
 * Source of truth:
 *   levels/reconstruct/*.json
 *
 * Runtime assets are generated by validate-levels.js:
 *   levels/index.json
 *   levels/catalog.generated.js
 */

const LEVEL_CATALOG_PATH = 'levels/index.json';
const LEVEL_MODES = ['reconstruct'];

window.__LEVEL_DATASET_BY_MODE__ = window.__LEVEL_DATASET_BY_MODE__ || {};
window.__ACTIVE_GAME_MODE__ = window.__ACTIVE_GAME_MODE__ || 'reconstruct';
window.LEVELS = window.LEVELS || [];
window.LEVELS_META = window.LEVELS_META || { groups: [] };

function inferDifficultyFromMoves(moveCount) {
    if (moveCount <= 4) return 1;
    if (moveCount <= 6) return 2;
    if (moveCount <= 8) return 3;
    if (moveCount <= 10) return 4;
    return 5;
}

function normalizeFace(face) {
    if (!face || typeof face.patternId !== 'string') {
        return null;
    }

    return {
        patternId: face.patternId,
        rotation: Number.isFinite(Number(face.rotation)) ? Number(face.rotation) : 0,
        flipHorizontal: Boolean(face.flipHorizontal),
        flipVertical: Boolean(face.flipVertical),
        x: Number.isFinite(Number(face.x)) ? Number(face.x) : undefined,
        y: Number.isFinite(Number(face.y)) ? Number(face.y) : undefined
    };
}

function normalizeFaceMap(faceMap) {
    if (!faceMap || typeof faceMap !== 'object') {
        return null;
    }

    const result = {};
    Object.keys(faceMap).forEach((key) => {
        const face = normalizeFace(faceMap[key]);
        if (face) {
            result[key] = {
                patternId: face.patternId,
                rotation: face.rotation,
                flipHorizontal: face.flipHorizontal,
                flipVertical: face.flipVertical
            };
        }
    });
    return result;
}

function normalizeNetFaces(netFaces, netPatterns) {
    if (Array.isArray(netFaces) && netFaces.length === 6) {
        return netFaces.map((face) => normalizeFace(face));
    }

    if (Array.isArray(netPatterns) && netPatterns.length === 6) {
        return netPatterns.map((patternId) => normalizeFace({
            patternId,
            rotation: 0
        }));
    }

    return [];
}

function buildDefaultGroups(levels) {
    const buckets = new Map();

    levels.forEach((level) => {
        const key = String(level.difficulty);
        if (!buckets.has(key)) {
            buckets.set(key, {
                key,
                difficulty: level.difficulty,
                minMoves: level.moveCount,
                maxMoves: level.moveCount,
                count: 0
            });
        }

        const bucket = buckets.get(key);
        bucket.minMoves = Math.min(bucket.minMoves, level.moveCount);
        bucket.maxMoves = Math.max(bucket.maxMoves, level.moveCount);
        bucket.count += 1;
    });

    return [...buckets.values()]
        .sort((a, b) => a.difficulty - b.difficulty)
        .map((bucket) => ({
            key: `tier-${bucket.difficulty}`,
            label: `Difficulty ${bucket.difficulty}`,
            description: `${bucket.minMoves}-${bucket.maxMoves} moves`,
            minMoves: bucket.minMoves,
            maxMoves: bucket.maxMoves,
            count: bucket.count
        }));
}

function normalizeLevel(level, index, mode) {
    const netFaces = normalizeNetFaces(level.netFaces, level.netPatterns);
    const path = Array.isArray(level.path) && level.path.length
        ? [...level.path]
        : (Array.isArray(level.prompt?.directions) ? [...level.prompt.directions] : []);
    const moveCount = level.moveCount ?? path.length ?? 0;
    const difficulty = level.difficulty ?? inferDifficultyFromMoves(moveCount);
    const promptObservedPathFaces = Array.isArray(level.prompt?.observedPathFaces)
        ? level.prompt.observedPathFaces
        : (Array.isArray(level.prompt?.observedStampFaces)
            ? level.prompt.observedStampFaces
            : level.prompt?.observedFaces);

    return {
        id: level.id ?? index + 1,
        code: level.code ?? `${mode.toUpperCase()}-${String(index + 1).padStart(3, '0')}`,
        mode,
        name: level.name ?? `${mode} level ${String(index + 1).padStart(3, '0')}`,
        description: level.description ?? `${mode} level with ${moveCount} moves`,
        netLayout: level.netLayout ?? 'standard_cross',
        netFaces,
        netPatterns: netFaces.map((face) => face.patternId),
        path,
        startX: level.startX ?? 0,
        startY: level.startY ?? 0,
        gridWidth: level.gridWidth ?? 5,
        gridHeight: level.gridHeight ?? 5,
        difficulty,
        moveCount,
        tier: level.tier ?? difficulty,
        tierLabel: level.tierLabel ?? `Difficulty ${difficulty}`,
        answers: level.answers
            ? {
                ...level.answers,
                bottomFaces: Array.isArray(level.answers.bottomFaces)
                    ? level.answers.bottomFaces.map(normalizeFace)
                    : null,
                solutionFaces: normalizeFaceMap(level.answers.solutionFaces),
                trueSolutionFaces: normalizeFaceMap(level.answers.trueSolutionFaces)
            }
            : null,
        targets: level.targets ?? null,
        prompt: level.prompt
            ? {
                ...level.prompt,
                directions: Array.isArray(level.prompt.directions) ? [...level.prompt.directions] : path,
                observedPathFaces: Array.isArray(promptObservedPathFaces)
                    ? promptObservedPathFaces.map(normalizeFace)
                    : [],
                observedStampFaces: Array.isArray(promptObservedPathFaces)
                    ? promptObservedPathFaces.map(normalizeFace)
                    : [],
                slotSequence: Array.isArray(level.prompt.slotSequence) ? [...level.prompt.slotSequence] : [],
                requiredSlots: Array.isArray(level.prompt.requiredSlots) ? [...level.prompt.requiredSlots] : [],
                requiredCount: Number.isFinite(Number(level.prompt.requiredCount))
                    ? Number(level.prompt.requiredCount)
                    : 0
            }
            : null,
        solutionFaces: normalizeFaceMap(level.answers?.solutionFaces ?? level.solutionFaces),
        trueSolutionFaces: normalizeFaceMap(level.answers?.trueSolutionFaces ?? level.trueSolutionFaces),
        gtBottomFaces: Array.isArray(level.answers?.bottomFaces)
            ? level.answers.bottomFaces.map(normalizeFace)
            : (Array.isArray(level.gtBottomFaces) ? level.gtBottomFaces.map(normalizeFace) : null),
        gtPatternSequence: Array.isArray(level.targets?.patternSequence)
            ? [...level.targets.patternSequence]
            : (Array.isArray(level.gtPatternSequence) ? [...level.gtPatternSequence] : null),
        sourceFile: level.sourceFile ?? null
    };
}

function normalizeModeEntry(mode, entry) {
    const rawLevels = Array.isArray(entry?.levels) ? entry.levels : [];
    const levels = rawLevels.map((level, index) => normalizeLevel(level, index, mode));
    const groups = Array.isArray(entry?.groups) && entry.groups.length
        ? entry.groups
        : buildDefaultGroups(levels);

    return {
        levels,
        meta: {
            groups,
            count: levels.length
        }
    };
}

function normalizeCatalog(catalog) {
    const modes = {};

    LEVEL_MODES.forEach((mode) => {
        modes[mode] = normalizeModeEntry(mode, catalog?.modes?.[mode]);
    });

    return {
        version: catalog?.version ?? 2,
        generatedAt: catalog?.generatedAt ?? null,
        modes
    };
}

function getLevelsForMode(mode) {
    return window.__LEVEL_DATASET_BY_MODE__[mode]?.levels ?? [];
}

function getMetaForMode(mode) {
    return window.__LEVEL_DATASET_BY_MODE__[mode]?.meta ?? { groups: [], count: 0 };
}

function syncActiveLevelsForMode(mode) {
    window.__ACTIVE_GAME_MODE__ = LEVEL_MODES.includes(mode) ? mode : 'reconstruct';
    window.LEVELS = getLevelsForMode(window.__ACTIVE_GAME_MODE__);
    window.LEVELS_META = getMetaForMode(window.__ACTIVE_GAME_MODE__);
    return {
        levels: window.LEVELS,
        meta: window.LEVELS_META
    };
}

async function loadLevelsBundle() {
    let catalog = window.__LEVEL_CATALOG_FALLBACK__ || { modes: {} };

    if (typeof fetch === 'function' && typeof window !== 'undefined') {
        try {
            const response = await fetch(`${LEVEL_CATALOG_PATH}?t=${Date.now()}`, { cache: 'no-store' });
            if (!response.ok) {
                throw new Error(`HTTP ${response.status}`);
            }
            catalog = await response.json();
        } catch (error) {
            console.warn('[levels] Falling back to generated catalog:', error);
        }
    }

    const normalized = normalizeCatalog(catalog);
    window.__LEVEL_DATASET_BY_MODE__ = normalized.modes;
    syncActiveLevelsForMode(window.__ACTIVE_GAME_MODE__ || 'reconstruct');
    return normalized;
}

window.getLevelsForMode = getLevelsForMode;
window.getLevelMetaForMode = getMetaForMode;
window.syncActiveLevelsForMode = syncActiveLevelsForMode;
window.loadLevelsBundle = loadLevelsBundle;
